### ISSUE TITLE
SMSC is receiving "TCP Zero Window Segment"

### ISSUE THREAD

**Issue by grmagalhaes** [python-smpplib/python-smpplib#120]
The SMSC is receiving "TCP Zero Window Segment" of our smpplib app. 
Has anyone experienced this problem?

Is there a way to increase smpplib's TCP Window Size?

**Comment by eigenein** [comment]
Oopsie, I've completely missed this question.

For the future: perhaps only by overriding `_create_socket` at the moment.

**Comment by fpalamour** [comment]
Hello,

Have you found a solution to your issue @grmagalhaes ? 

I'm currently facing the same issue. I use the lib to deal with a large amount of SMS, and sometimes, when traffic is high, the SMSC told me they're receiving a TCP zero window segment when the lib can't keep up with the many deliver_sm pdus that are sent. We could see that there might be a 20 minutes difference between the time they send a deliver_sm and the time I receive it. Since I'm basically pushing the deliver_sm pdus in a queue to process them later, I can't see how I could go any faster.  So I started learning about TCP socket and how it works and it seems like the socket sends a TCP zero window segment when its buffer becomes too big to be able to process any more data, so it asks the sender to slow down for a second. Would you have any suggestions on how to rewrite the _create_socket function  to process data faster ?  In the mean time, I'll keep this issue updated if I find anything relevant so it can help anyone having the same issue.

**Comment by podshumok** [comment]
You might be at the limit of what library or your app can do. Id est this is a performance issue.
Here are some things to keep in mind or consider:
- You application is limited by GIL, if you are pushing `deliver_sm` to some queue and than shovel it up in a different thread (but in the same process), you're not going to speed up anything, push to another process instead
- sometimes it is easy to try `greenlets` you application might run somewhat faster without any significant changes, see their readme for the drawbacks
- use a non-blocking mode of the socket. The implementation was merged into master some time ago, but we don't have any docs yet. The idea is that when there are no messages in the socket at the moment, you application can switch to another socket (i.g. the one for the database) and do something there instead.
- try running your app with PyPy instead of cPython: again, it's likely that everything will just work without any other modifications
- try running you application under a profiler to identify the bottlenecks, if you'll find that they are related to the library, please report them as a separate issue.

**Comment by fpalamour** [comment]
Thank you for your reply.

When I say that I push the deliver_sm to a queue, I meant a rabbitmq queue, not a python queue, I should have been more specific. I've read a bit about non-blocking and select already and from what you're saying and from what I understand, it's not much use for me cause my issue is that, I guess, the data received by the socket is buffered by the OS, waiting for it to be read, is that correct ? So the issue is not about doing something else when there's nothing to read, it's quite the opposite actually, there's too much to read.

Thank you for your recommendations I'll try to document myself on each one of them and I'll keep the issue updated if I find anything that helps me with my current issue.
