### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf8' in position 120: ordinal not in range(128)

### ISSUE THREAD

**Issue by sabareeshwaran-plivo** [python-smpplib/python-smpplib#37]
1. The code which you have given will send unicode text as message but how can i send a normal text. 
when i send normal text am getting 

```
Traceback (most recent call last):
    client.listen()
  File "build/bdist.macosx-10.12-x86_64/egg/smpplib/client.py", line 326, in listen
  File "build/bdist.macosx-10.12-x86_64/egg/smpplib/client.py", line 279, in read_once
  File "build/bdist.macosx-10.12-x86_64/egg/smpplib/client.py", line 219, in read_pdu
  File "build/bdist.macosx-10.12-x86_64/egg/smpplib/smpp.py", line 46, in parse_pdu
    text_type = str(filter(str.isalpha, str(text.encode('utf-8'))))
  File "build/bdist.macosx-10.12-x86_64/egg/smpplib/pdu.py", line 133, in parse
  File "build/bdist.macosx-10.12-x86_64/egg/smpplib/command.py", line 334, in parse_params
  File "build/bdist.macosx-10.12-x86_64/egg/smpplib/command.py", line 349, in parse_optional_params
  File "build/bdist.macosx-10.12-x86_64/egg/smpplib/command.py", line 75, in get_optional_name
smpplib.exceptions.UnknownCommandError: Unknown SMPP command code "0x1402"
DEBUG:smpplib.client:Sending unbind PDU
DEBUG:smpplib.client:Waiting for PDU...
DEBUG:smpplib.client:Read unbind_resp PDU
INFO:smpplib.client:Disconnecting...
```

2. i need to send normal text, unicode text and \x unicode characters but not as parts. all the text upto the allowed text length have to be sent as a single message else it should throws `MessageTooLong` but am getting `unicodeDecodeError`
```
UnicodeEncodeError: 'ascii' codec can't encode character u'\xef' in position 120: ordinal not in range(128)
```

**Comment by podshumok** [comment]
I'm not sure I got your question right, but it looks like you should use `gsm.make_parts()` function and raise `MessageTooLong` (or any other) exception yourself it number of parts is more than 1.

**Comment by sabareeshwaran-plivo** [comment]
am using gsm.make_parts but sending plain text is working but unable to send /x unicode characters.

**Comment by sabareeshwaran-plivo** [comment]
client.listen()
  File "build/bdist.macosx-10.12-x86_64/egg/smpplib/client.py", line 326, in listen
  File "build/bdist.macosx-10.12-x86_64/egg/smpplib/client.py", line 279, in read_once
  File "build/bdist.macosx-10.12-x86_64/egg/smpplib/client.py", line 219, in read_pdu
  File "build/bdist.macosx-10.12-x86_64/egg/smpplib/smpp.py", line 46, in parse_pdu
    text = generate_unicode(int(length), text_type.lower())
  File "build/bdist.macosx-10.12-x86_64/egg/smpplib/pdu.py", line 133, in parse
  File "build/bdist.macosx-10.12-x86_64/egg/smpplib/command.py", line 334, in parse_params
  File "build/bdist.macosx-10.12-x86_64/egg/smpplib/command.py", line 349, in parse_optional_params
  File "build/bdist.macosx-10.12-x86_64/egg/smpplib/command.py", line 75, in get_optional_name
smpplib.exceptions.UnknownCommandError: Unknown SMPP command code "0x1402"


getting this error when waiting for dlr but i got the message delivered

**Comment by podshumok** [comment]
That is related to #2: library cannot parse vendor-specific delivery code.

**Comment by whyteks** [comment]
@sabareeshwaran-plivo 
In relation to your part 2. and the UnicodeEncodeError
If you have not resolved this (and I could be way off here), but check to make sure that your source_addr and destination_addr are byte strings and not unicode. 
That bit me just now.

**Comment by nikoladsp** [comment]
Hi, I run into a same (or similar) problem. Sending of some Arabic messages are failing due the: `UnicodeDecodeError: 'ascii' codec can't decode byte 0x8f in position 3: ordinal not in range(128)`. This does not happen all the time, but looks like some characters in the text message are causing this behavior. I am having a trouble to debug since does not have access to SMPP server. All 3 fields: to, from and message are unicode. How (or shall I) convert them in order recipient receives proper message instead of bunch of unicode characters?

Thank you kindly

**Comment by whyteks** [comment]
@nikoladsp Can you capture (tcpdump or wireshark) the smpp transaction with an offending PDU?

**Comment by nikoladsp** [comment]
@whyteks I manage to resolve, it was my error, but still not expected: when I sent everything in ASCII (plain English) - it worked. All of the inputs was still Unicode Python string, since it was made by REST endpoint. also I tried cyrilic letters, this also worked, however - when started using eg Greek symbols - it start giving the error. After few days of debug, I discovered that I also must encode recipient and sender with utf-8. It was misleading for me why it worked with Serbian and not Greek and only after this I understood documentation comment in send SMS sample.

Another question I have is this: after sending the message with **send_message**: how can I get message ID? I see only sequence Id in returned fields.

Thank you kindly

**Comment by eigenein** [comment]
@nikoladsp Message ID is contained in the PDU you receive afterwards, sort of:

```python
client.send_message(...)
print(client.read_pdu().message_id)
```

**Comment by nikoladsp** [comment]
Thanks. My use case is as follows: there are multiple worker threads sending SMS by putting them in the queue. In queue, one by one message is processed in order to have only one connection to the SMPP server (provider restriction). After I call **send_message()** I store returned results (PDUs) in a queue and later on when **on_send** and/or **on_received** are called I try to use returned message_id to find message in the queue and update its status, so I cant rely on order but must have **message_id**.

Is it safe to call **client.read_pdu().message_id** just after **send_message**? Also, are TLVs supported by the library atm?

Thank you kindly.

**Comment by eigenein** [comment]
Though what I said is correct, perhaps I still misunderstood your question a bit.

Indeed, you need to use `set_message_sent_handler` and `set_message_received_handler`. `message_sent_handler` receives a PDU as parameter and `pdu.message_id` gives you ID of the message being sent. `message_received_handlers` also receives the `pdu` parameter and `pdu.receipted_message_id` refers to the message that is delivered.

Also, keep in mind that every part of a multipart SMS gets its own ID.

Did you want to say that this is not working for you?

**Comment by nikoladsp** [comment]
Well, I dont know MSPP protocol to say the truth. SMPP server provider does not share its settings nor the logs, so I have to create serialization of incoming SMPP requests. I tried obtaining message_id as you suggested (right after I issue send_message). What I am not sure in which handler of those 2  I should wait for the response from server that message has its status changed: I am interested in events like: message is delivered to the mobile phone (which can occur much  later then I sent it) or message is deleted (when phone owner is not turning on the phone for 2 or 3 days or something like that). This is why I might wish to 'poll' for message status later

Thank you!

PS: I sent you private mail asking for professional help by renting your service

**Comment by eigenein** [comment]
Basically, you have two options:

1. You can poll the message status periodically, this is done by `QuerySM` and we don't have it yet. There's an issue for that: https://github.com/python-smpplib/python-smpplib/issues/21. Perhaps, this is not really an option if you send a lot of messages.
2. You can ask SMPP server to notify you of the status changes. For that you register a handler with `set_message_received_handler` **and** you must set `registered_delivery=True` when you call `send_message`. Then you'll receive notifications with one of these statuses: https://github.com/python-smpplib/python-smpplib/blob/master/smpplib/consts.py#L253-L261

**Comment by eigenein** [comment]
Hi @nikoladsp,

Can I close the issue?
